[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-webgl"
version = "0.1.0"

[features]
shadergraph = ["rendiation-shadergraph"]

[dependencies]
js-sys = "0.3.45"
wasm-bindgen = {version = "0.2.68"}

rendiation-algebra = {path = "../../../math/algebra"}
rendiation-ral = {path = "../../core"}
rendiation-shadergraph = {path = "../../../shader-graph", optional = true}

[dependencies.web-sys]
features = [
  'Document',
  'Element',
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGl2RenderingContext',
  'WebGlProgram',
  'WebGlUniformLocation',
  'WebGlShader',
  'WebGlTexture',
  'WebGlFramebuffer',
  'Window',
]
version = "0.3.39"
