[package]
edition = "2018"
name = "rendiation-rendergraph"
version = "0.0.1"

[dependencies]
arena-graph = {path = "../../utils/arena-graph"}
rendiation-algebra = {path = "../../math/algebra"}
rendiation-geometry = {path = "../../math/geometry"}
rendiation-ral = {path = "../../ral/core"}
rendiation-renderable-mesh = {path = "../../mesh/renderable"}
rendiation-webgpu = {path = "../../ral/backend/webgpu", optional = true}

[features]
webgpu = ["rendiation-webgpu"]
