[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-shadergraph"
version = "0.1.0"

[dependencies]
arena-graph = {path = "../../utils/arena-graph"}
lazy_static = "1.4.0"
naga = {version = "0.3.1", features = ["glsl-in", "glsl-out", "spv-out"]}
rendiation-algebra = {path = "../math/algebra"}
