[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "fontext"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
font-loader = "0.11.0"
linked-hash-map = "0.5.4"
rendiation-algebra = { path = "../../math/algebra" }
rendiation-color = { path = "../color" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-texture-core = { path = "../texture/core" }
rendiation-texture-packer = { path = "../texture/packer" }

glyph_brush = { version = "0.7", optional = true }

[features]
default = ["glyph_brush_impl"]
glyph_brush_impl = ["glyph_brush"]

[lints]
workspace = true
