[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-canvas-gpu"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
fontext = { path = "../../fontext" }
lyon = "1.0.1"
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-canvas-core = { path = "../core" }
rendiation-color = { path = "../../color" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }

[lints]
workspace = true
