[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "wgsl-codegen-graph"
version = "0.1.0"

[dependencies]
shadergraph = {path = "../../../graph"}
fast-hash-collection = {path = "../../../../utils/fast-hash-collection"}
linked_hash_set = "0.1.4"
