[package]
edition = "2021"
name = "rendiation-scene-gltf-loader"
version = "0.0.1"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
fast-hash-collection = { path = "../../../../utility/fast-hash-collection" }
gltf = "1.2.0"
half = "*"
rendiation-algebra = { path = "../../../../math/algebra" }
rendiation-geometry = { path = "../../../../math/geometry" }
rendiation-mesh-core = { path = "../../../../content/mesh/core" }
rendiation-scene-core = { path = "../../../core" }
rendiation-shader-api = { path = "../../../../shader/api" }
rendiation-texture = { path = "../../../../content/texture/core" }

[lints]
workspace = true
