[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-webgpu"
version = "0.1.0"

[dependencies]
anymap = "0.12.1"
arena = { path = "../../utility/arena" }
bitflags = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
dyn-clone = { workspace = true }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
futures = { workspace = true }
incremental = { path = "../../utility/incremental" }
linked-hash-map = "0.5.4"
log = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-color = { path = "../../content/color" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-lighting-ibl-core = { path = "../../content/lighting/ibl/core" }
rendiation-lighting-transport = { path = "../../content/lighting/transport" }
rendiation-mesh-core = { path = "../../content/mesh/core" }
rendiation-mesh-gpu-system = { path = "../../content/mesh/gpu-system" }
rendiation-scene-core = { path = "../core" }
rendiation-shader-api = { path = "../../shader/api" }
rendiation-shader-library = { path = "../../shader/library" }
rendiation-texture = { path = "../../content/texture/core" }
rendiation-texture-gpu-system = { path = "../../content/texture/gpu-system" }
rendiation-texture-gpu-process = { path = "../../content/texture/gpu-process" }
rendiation-texture-gpu-base = { path = "../../content/texture/gpu-base" }
tree = { path = "../../utility/tree" }

reactive = { path = "../../utility/reactive" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }

[lints]
workspace = true
