[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-webgpu"
version = "0.1.0"

[features]
glsl-spirv = ["glsl-to-spirv"]
shadergraph = ["rendiation-shadergraph"]

[dependencies]
glsl-to-spirv = {version = "0.1", optional = true}
wgpu = "0.7.0"

rendiation-algebra = {path = "../../../math/algebra"}
rendiation-geometry = {path = "../../../math/geometry"}

rendiation-ral = {path = "../../core"}
rendiation-shadergraph = {path = "../../../shader-graph", optional = true}
