[package]
edition = "2021"
name = "dyn-downcast"
version = "0.0.1"

[dependencies]
fast-hash-collection = { path = "../fast-hash-collection" }
once_cell = { workspace = true }
paste = { workspace = true }
parking_lot = { workspace = true }

[lints]
workspace = true
