[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2018"
name = "rendiation-ral"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
arena = {path = "../../utils/arena"}
wgpu-types = "0.7"
